### ISSUE TITLE
=sys-apps/man-db-2.8.1 with USE="seccomp" fails to open man pages.

### ISSUE THREAD

**Issue by lluixhi** [gentoo/musl#100]
```
man: bzip2: Bad system call
man: bzip2: Bad system call
man: bzip2: Bad system call
man: bzip2: Bad system call
man: bzip2: Bad system call
man: command exited with status 2: /usr/libexec/man-db/zsoelim | /usr/libexec/man-db/manconv -f UTF-8:ISO-8859-1 -t UTF-8//IGNORE | preconv -e UTF-8 | tbl | nroff -mandoc -c -rLL=230n -rLT=230n -Tutf8
```

The syscall filter likely needs to be adjusted.

**Comment by lluixhi** [comment]
Error only exists in man-db-2.8.1, so they probably hadn't corrected the list of allowed syscalls -- package could be masked in tree, or removed in ::gentoo

**Comment by gyakovlev** [comment]
Looks like it's not musl-specific.

MAN_DISABLE_SECCOMP=1 is a temp workaround.

https://bugs.gentoo.org/650764
https://bugs.gentoo.org/650384

upstream has some commits that adjust the filter.

https://git.savannah.gnu.org/cgit/man-db.git/commit/?id=232899c9776625e75cec72a4fb9e588968a6fa2f

https://git.savannah.gnu.org/cgit/man-db.git/commit/?id=ecba2e037bcb33b7fd4f0caa7bc42bd05fefdfd6

adding madvise, kill, tgkill to the whitelist  will likely resolve the issues
debian and arch also have similar bugs..

the funny thing is that the nroff related bug only happened in a chroot for me, but not after I booted the system.

**Comment by blueness** [comment]
yeah not musl specific.  this needs to be fixed in the tree.
