### ISSUE TITLE
sys-kernel/dracut: stable keyworded ebuild requires unstable fts-standalone

### ISSUE THREAD

**Issue by gyakovlev** [gentoo/musl#102]
amd64 keyworded  dracut::musl fails to build with amd64 keyworded fts-standalone-0.2-r1::gentoo, because that version of fts-standalone does not provide pkgconfig file.

bullds fine with fts-standalone-1.2.7::gentoo tho (which is ~amd64) as it does provide pkgconfig file.

No logs this time, sorry.

Not sure how to deal with cross-repo keywording and on musl in general.
My guess is that fts-standalone-1.2.7::gentoo needs stable keyword for amd64 or 0.2-r1 needs to provide a .pc file.

**Comment by blueness** [comment]
Okay so stabilizing  fts-standalone-1.2.7::gentoo would be sufficient?  If so, do you want to open a bug on bugs.gentoo.org so it can track it properly.

**Comment by gyakovlev** [comment]
Yes, merging fts-standalone-1.2.7 with  ~amd64 keywords and dracut stable builds fine with it. I can boot the system. even booting with zfs works.

on the other hand fts-standalone is used by other stuff, namely: pax, elfutils, libzip.

I've done basic build-testing with the following results:

elfutils is masked and conflicts with libelf. I don't really understand this ELF stuff currently and how to handle the situation, leave it to you.
libzip::getoo builds fine with fts-standalone-1.2.7
pax::gentoo fails, which is expected.
pax::musl is ~amd64, and builds just fine with  fts-standalone-1.2.7
libselinux::musl builds fine.
dracut::gentoo fails, as expected.
dracut::musl build fine and works fine, that one I've tested.


I'll open a bug and get back here with a number.

**Comment by gyakovlev** [comment]
bug is here
https://bugs.gentoo.org/649670

I can work on it and open a PR if you would like to, just lemme know which solution is preferred.

**Comment by lluixhi** [comment]
@gyakovlev 
Just FYI, I've been running the patched elfutils from this overlay with fts-standalone for about half a year now? It appears to work just fine.

I mean a lot of these things should probably be pushed into ::gentoo at this point, but there are some dirty patches that break GLIBC support and I haven't gotten around to it yet.

**Comment by blueness** [comment]
i stabilized fts-standalone-1.27.  let me know if it fixes the above problems and/or introduces new problems.
