### ISSUE TITLE
Qbittorrent

### ISSUE THREAD

**Issue by g3ngr33n** [gentoo/musl#104]
Topic regarding the problem 

https://forums.gentoo.org/viewtopic-p-8196860.html

Here what I purpose 

[qbittorrent-4.0.4-musl.patch.txt](https://github.com/gentoo/musl/files/1819255/qbittorrent-4.0.4-musl.patch.txt)

[qbittorrent-4.0.4.ebuild.txt](https://github.com/gentoo/musl/files/1819256/qbittorrent-4.0.4.ebuild.txt)

Hope it's help

**Comment by blueness** [comment]
this looks reasonable.  why not create a proper pull request and i'll just commit it.

**Comment by g3ngr33n** [comment]
will do

**Comment by g3ngr33n** [comment]
I'm not sure why my pull request fail with the Travis test, did I do something wrong ?

**Comment by blueness** [comment]
i'll take care of it.

**Comment by g3ngr33n** [comment]
Thanks
