### ISSUE TITLE
irssi 1.1.1 fail to build with socks5 useflag

### ISSUE THREAD

**Issue by g3ngr33n** [gentoo/musl#108]
> core/ -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -march=skylake -O2 -pipe -Wall -DSOCKS  -c -o irssi.o irssi.c
> irssi.c: In function ‘main’:
> irssi.c:293:2: warning: implicit declaration of function ‘SOCKSinit’ [-Wimplicit-function-declaration]
>   SOCKSinit(argv[0]);
>   ^~~~~~~~~
> x86_64-gentoo-linux-musl-gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src -I../../src/core/ -I../../src/fe-common/core/ -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -march=skylake -O2 -pipe -Wall -DSOCKS  -c -o module-formats.o module-formats.c
> /bin/sh ../../libtool  --tag=CC   --mode=link x86_64-gentoo-linux-musl-gcc  -march=skylake -O2 -pipe -Wall -DSOCKS  -export-dynamic -Wl,-O1 -Wl,--as-needed -o irssi gui-entry.o gui-expandos.o gui-printtext.o gui-readline.o gui-windows.o lastlog.o mainwindows.o mainwindow-activity.o mainwindows-layout.o statusbar.o statusbar-config.o statusbar-items.o term.o term-terminfo.o terminfo-core.o textbuffer.o textbuffer-commands.o textbuffer-view.o irssi.o module-formats.o ../fe-common/irc/libfe_common_irc.a ../fe-common/irc/dcc/libfe_irc_dcc.a ../fe-common/irc/notifylist/libfe_irc_notifylist.a ../fe-common/core/libfe_common_core.a  ../irc/libirc.a ../irc/core/libirc_core.a ../irc/dcc/libirc_dcc.a ../irc/flood/libirc_flood.a ../irc/notifylist/libirc_notifylist.a ../core/libcore.a ../lib-config/libirssi_config.a -lsocks -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -lssl -lcrypto -lncursesw  
> libtool: link: x86_64-gentoo-linux-musl-gcc -march=skylake -O2 -pipe -Wall -DSOCKS -Wl,-O1 -Wl,--as-needed -o irssi gui-entry.o gui-expandos.o gui-printtext.o gui-readline.o gui-windows.o lastlog.o mainwindows.o mainwindow-activity.o mainwindows-layout.o statusbar.o statusbar-config.o statusbar-items.o term.o term-terminfo.o terminfo-core.o textbuffer.o textbuffer-commands.o textbuffer-view.o irssi.o module-formats.o -Wl,--export-dynamic -pthread -Wl,--export-dynamic  ../fe-common/irc/libfe_common_irc.a ../fe-common/irc/dcc/libfe_irc_dcc.a ../fe-common/irc/notifylist/libfe_irc_notifylist.a ../fe-common/core/libfe_common_core.a ../irc/libirc.a ../irc/core/libirc_core.a ../irc/dcc/libirc_dcc.a ../irc/flood/libirc_flood.a ../irc/notifylist/libirc_notifylist.a ../core/libcore.a ../lib-config/libirssi_config.a -lsocks -lgmodule-2.0 -lglib-2.0 -lssl -lcrypto -lncursesw -pthread
> /usr/lib/gcc/x86_64-gentoo-linux-musl/6.4.0/../../../libsocks.so: undefined reference to `bindresvport'
> collect2: error: ld returned 1 exit status
> make[3]: *** [Makefile:525: irssi] Error 1
> make[3]: Leaving directory '/var/tmp/portage/net-irc/irssi-1.1.1/work/irssi-1.1.1/src/fe-text'
> make[2]: *** [Makefile:445: all-recursive] Error 1
> make[2]: Leaving directory '/var/tmp/portage/net-irc/irssi-1.1.1/work/irssi-1.1.1/src'
> make[1]: *** [Makefile:543: all-recursive] Error 1
> make[1]: Leaving directory '/var/tmp/portage/net-irc/irssi-1.1.1/work/irssi-1.1.1'
> make: *** [Makefile:423: all] Error 2
>  * ERROR: net-irc/irssi-1.1.1::gentoo failed (compile phase):
>  *   emake failed

Any idea ?

**Comment by SJLC** [comment]
It looks to me like it needs `-ltirpc`  when linking against musl, since that's where symbol `bindresvport` lives

**Comment by anarchpenguin** [comment]
Closing as 1.2.2 compiles fine with socks5 useflag enabled.
