### ISSUE TITLE
Firejail 0.9.52 - libtrace.c: In function ‘log_exec’:

### ISSUE THREAD

**Issue by g3ngr33n** [gentoo/musl#109]
> libtrace.c: In function ‘log_exec’:
> libtrace.c:683:18: error: ‘PATH_MAX’ undeclared (first use in this function)
>   static char buf[PATH_MAX + 1];
>                   ^~~~~~~~
> libtrace.c:683:18: note: each undeclared identifier is reported only once for each function it appears in
> 

Which make the build fail. I fixed it with this small patch, take a look and tell me if it is right and I will pull request

```
--- a/src/libtrace/libtrace.c
+++ b/src/libtrace/libtrace.c
@@ -29,7 +29,9 @@
 #include <arpa/inet.h>
 #include <sys/un.h>
 #include <sys/stat.h>
+#include <syslog.h>
 #include <dirent.h>
+#include <limits.h>

 // break recursivity on fopen call
 typedef FILE *(*orig_fopen_t)(const char *pathname, const char *mode)
```

**Comment by blueness** [comment]
make a PR.  Also this patch should go upstream.

**Comment by g3ngr33n** [comment]
I did PR the firejail repo directly
