### ISSUE TITLE
automatically masking ::gentoo packages if one present in this repo

### ISSUE THREAD

**Issue by gyakovlev** [gentoo/musl#110]
I have a stupid script that masks every package in ::gentoo that is also in ::musl
Makes updating much easier when package in gentoo gets an update and it's not backported yet.

That way portage always picks ::musl version.

```bash
#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
truncate --size=0 /etc/portage/package.mask/musl.conf
for atom in $(qatom -F '%{CATEGORY}/%{PN}' $(portageq --no-filters --repo musl) | sort -u);
	do printf "%s::gentoo\n" "$atom" >> /etc/portage/package.mask/musl.conf;
done
```

One can  put this into /etc/portage/repo.postsync.d
Of course the script is just an example, it should be improved.

Any thoughts on this? Can and should something like this be used for this repo?

**Comment by blueness** [comment]
Its a cool script but its a dangerous approach for several reasons, not the least of which forgetting about the masks when you should be bumping.
