### ISSUE TITLE
[information] What should be done

### ISSUE THREAD

**Issue by g3ngr33n** [gentoo/musl#112]
Hello,

Would like to known what should be do when a ebuild stable isn't working with musl but the ~amd64 (not stable one) work just fine.

Example 

net-analyzer/traceroute stable (2.0.20) have a lot of issue (AI_IDN, header to fix...) but the 2.1.0 is perfect.

I would like to have portage to pickup automatically the 2.1.0  with the [1] "musl" showed, how this work ? should I simply commit the ebuild in this repo or there is another way to define which version to pickup for musl ?

Thanks

**Comment by lluixhi** [comment]
I believe you can add a line to `/etc/portage/package.accept_keywords` that says `net-analyzer/traceroute ~amd64` for the time being

**Comment by blueness** [comment]
this is not really a bug.  if you want, you can copy the ebuild for traceroute 2.1.0 to the overlay and mark it stable there, then open a PR request.  alternatively you can open a gentoo bug asking for 2.1.0 to be stabilized and can say that it fixes issues on gentoo.

the title of this bug report is too vague.  a developer sorts his bugs based on the title.  something like "what's to be done" will most likely get ignore.  a better title is "net-analyzer/traceroute-2.0.20 fails to build on musl".
