### ISSUE TITLE
Apparmor 2.12.0 with getenv_secure and scandirat 

### ISSUE THREAD

**Issue by g3ngr33n** [gentoo/musl#115]
2 patch to check, I could emerge apparmor but aren't sure that they are both ok for a pull.

{ Deleted, those patch aren't good }

Thanks

**Comment by blueness** [comment]
its inconvenient to work with them that way.  start the pr and i'll comment there

**Comment by blueness** [comment]
please only do pull requests.  i can't review these.

**Comment by g3ngr33n** [comment]
Hello,

I have give some of my time to make apparmor working, available at : 

https://github.com/g3ngr33n/apparmor-musl-gentoo/

I actually use apparmor on my musl gentoo system for ~1 week and so far I haven't spot any bug / problem with the proposed ebuild

I also included a patch for firejail with fix the building error with the useflag apparmor

As apparmor isn't a small feature, I decided before to make a pull request, to create a repo where it can be tested, improved... Any feedback or help is the most welcome

**Comment by blueness** [comment]
please make a pull request against the musl overlay.  i can't review what you've given me.

**Comment by g3ngr33n** [comment]
I can make a pull request but I think a review of this work should be made by someone with more skill to make everything is ok 

All the work is available at : https://github.com/g3ngr33n/apparmor-musl-gentoo/ 

If you still want the pull request I will do it.

**Comment by blueness** [comment]
sorry, i don't have time to do that.

**Comment by g3ngr33n** [comment]
I understand that, I will pull request when I'm more confident about this patch

Thanks

**Comment by g3ngr33n** [comment]
New pull request tested.

Remove the old pull request (24 march) it seem a conflict with the old / new make fail the travis build

**Comment by g3ngr33n** [comment]
As much as I tried, I can't give more time on it, I'm not familiar with git / travis to find out what's wrong with my pull request. The proposed patch and ebuild work that's all I known.

I have commit few minutes ago the last clean of the ebuild/patch for apparmor on my repo, if someone known travis and want to pull request what I have done so far...

**Comment by blueness** [comment]
i went with @milkey-mouse 's PR which was very close to yours but had the advantage of breaking out the musl patch into individual issues.  thanks for the contribution!
