### ISSUE TITLE
firefox-60.0 build failure with musl on amd64

### ISSUE THREAD

**Issue by lluixhi** [gentoo/musl#137]
So it turns out in liblibc in rust for musl amd64 and in the musl amd64 C headers, struct cmsghdr is defined something like this:
```
struct cmsghdr {
	socklen_t cmsg_len;
	int __pad1;
	int cmsg_level;
	int cmsg_type;
};
```

Unfortunately all other linux arches that use cmsghdr lack the `__pad1` field.

In firefox 60.0, `media/audioipc/audioipc/src/cmsg.rs`, the cmsghdr struct is initialized but it doesn't supply a default value for __pad1, so the build fails:

```
26:58.52    Compiling audioipc v0.2.1 (file:///var/tmp/portage/www-client/firefox-60.0/work/firefox-60.0/media/audioipc/audioipc)
26:59.51 error[E0063]: missing field `__pad1` in initializer of `libc::cmsghdr`
26:59.52    --> media/audioipc/audioipc/src/cmsg.rs:109:27
26:59.52     |
26:59.52 109 |             let cmsghdr = cmsghdr {
26:59.52     |                           ^^^^^^^ missing `__pad1`
26:59.52
27:00.56 error: aborting due to previous error
27:00.56
27:00.64 error: Could not compile `audioipc`.
27:00.64 warning: build failed, waiting for other jobs to finish...
27:23.34 error: build failed
```

Do we need to patch liblibc in rust or is it possible to fix this in firefox without breaking support for other arches? I'm not super familiar with rust.

**Comment by lluixhi** [comment]
Judging by this issue there may not be an easy way to do it yet: https://github.com/rust-lang/rfcs/issues/1594

So I'm going to add a patched firefox ebuild.

**Comment by stefson** [comment]
Have you done some runtime testing on this? Do we have a working firefox with these patches? I can't boot into my amd64 at the moment, busy with other stuff.

**Comment by lluixhi** [comment]
Hmmm.. yeah I have a working firefox 60 with those patches
