### ISSUE TITLE
Flatpak not building on musl

### ISSUE THREAD

**Issue by gitlab-j** [gentoo/musl#145]
Hi there, 

Flatpak from the flatpak-overlay won't currently build on musl. A working patch (from alpine) is here:

```
--- a/config.h.in
+++ b/config.h.in
@@ -140,3 +140,14 @@
 
 /* Define to 1 if you need to in order for `stat' and other things to work. */
 #undef _POSIX_SOURCE
+
+/* taken from glibc unistd.h and fixes musl */
+#ifndef TEMP_FAILURE_RETRY
+#define TEMP_FAILURE_RETRY(expression) \
+  (__extension__                                                              \
+    ({ long int __result;                                                     \
+       do __result = (long int) (expression);                                 \
+       while (__result == -1L && errno == EINTR);                             \
+       __result; }))
+#endif
+
```

**Comment by j-jd** [comment]
Also, it requires sys-fs/libostree:

--- a/config.h.in
+++ b/config.h.in
@@ -140,3 +140,14 @@
 
 /* Define to 1 if you need to in order for `stat' and other things to work. */
 #undef _POSIX_SOURCE
+
+/* taken from glibc unistd.h and fixes musl */
+#ifndef TEMP_FAILURE_RETRY
+#define TEMP_FAILURE_RETRY(expression) \
+  (__extension__                                                              \
+    ({ long int __result;                                                     \
+       do __result = (long int) (expression);                                 \
+       while (__result == -1L && errno == EINTR);                             \
+       __result; }))
+#endif
+

**Comment by blueness** [comment]
again, prepare a pull request

**Comment by j-jd** [comment]
Is there any chance I can submit it through bugzilla/gentoo? I've moved to Gitlab...

**Comment by blueness** [comment]
yes you can submit the patch elsewhere and just link here

**Comment by gitlab-j** [comment]
Closed, filing a bug report

**Comment by gitlab-j** [comment]
Moved here: https://github.com/fosero/flatpak-overlay/issues/28 since I'm not sure if it's a Gentoo issue?

**Comment by okias** [comment]
Upstream issue: https://github.com/flatpak/flatpak/issues/618
