### ISSUE TITLE
current stable in tree dev-vcs/git does not compile

### ISSUE THREAD

**Issue by stefson** [gentoo/musl#17]
There is a compile error with musl at least since 2.10.2, which is now the stable version in the gentoo tree. There is a patch available and we are having the fixed version 2.11 in the musl overlay. However, on a fresh install you will need to merge dev-vcs/git **first** and later on add the overlay including the fixed ebuild. 

How is the status of this? Does upstream know about it, is there a gentoo bug available? 

Meanwhile I would like to see the stable version 2.10.2 inherited into the overlay, was it deleted on purpose? Will create later a pullrequest for the overlay, or try to revert the commit that deletetd it if there is one, and I can find it.

**Comment by lluixhi** [comment]
Upstream doesn't know about it because I haven't filed a bug on the bugtracker for it.

2.10.2 was in the overlay, but I removed it because at the time it was unstable -- adding it again.

**Comment by stefson** [comment]
As you propably wrote the patch to adress the issue, do you think you could send it upstream? I doubt to be helpfull with it, honestly lacking of eperience and the know how. 

But I could open a bug report for gentoo, in case you feel it would be helpfull?

**Comment by lluixhi** [comment]
I opened a pull request here:
https://github.com/gentoo/gentoo/pull/3237
And a bug report here:
https://bugs.gentoo.org/603710

**Comment by stefson** [comment]
Well done, thank you! I am going to close this issue here for now, as it is back to the overlay and on the way to the tree.
