### ISSUE TITLE
Rust 1.29.1 + cargo 0.30.0

### ISSUE THREAD

**Issue by g3ngr33n** [gentoo/musl#196]
I made those ebuild which are needed to build the src of Firefox 60 <

The problem is only x86_64 arch is available for rust in this version (https://portage.smaeul.xyz/distfiles/), the higher version (1.30.1) fail to build with an unknown gentoo-musl-linux arch symbol error. 

Should I make a pull request or is it useless ?

**Comment by blueness** [comment]
how does this relate to the work done in issue/44 ?

**Comment by g3ngr33n** [comment]
You right I will have to test firefox 60+ on the related problem of this issue, I haven't much time now, will try to do it end of January

**Comment by g3ngr33n** [comment]
Indeed, eix-sync strangly did not update layman as usual.

**Comment by g3ngr33n** [comment]
Yes indeed, will test the smaeul ebuild. It should probably be available on the musl repo.

**Comment by stefson** [comment]
please open a pullrequest, if you've tested successfully.

**Comment by smaeul** [comment]
@stefson All of the libraries are still installed to `/usr/lib/rustlib/${CHOST}/lib`. They just aren't duplicated in `/usr/lib` anymore.

I've also updated to 1.31.1.

**Comment by stefson** [comment]
firefox can't find the correct std library, and I think this is because you seem to have renamed the chost to `x86_64-gentoo-linux-musl` instead of `x86_64-unknown-linux-musl` 

```
 0:20.49 DEBUG: Executing: `/usr/bin/rustc --crate-type staticlib --target=x86_64-unknown-linux-musl -o /var/tmp/portage/www-client/firefox-60.4.0/temp/conftestqhDFoQ.rlib /var/tmp/portage/www-client/firefox-60.4.0/temp/conftestNUIs_h.rs`
 0:20.49 DEBUG: The command returned non-zero exit status 1.
 0:20.49 DEBUG: Its error output was:
 0:20.49 DEBUG: | error[E0463]: can't find crate for `std`
 0:20.49 DEBUG: |   |
 0:20.50 DEBUG: |   = note: the `x86_64-unknown-linux-musl` target may not be installed
 0:20.50 DEBUG: |
 0:20.50 DEBUG: | error: aborting due to previous error
 0:20.50 DEBUG: |
 0:20.50 DEBUG: | For more information about this error, try `rustc --explain E0463`.
 0:20.50 ERROR: Cannot compile for x86_64-gentoo-linux-musl with /usr/bin/rustc
 0:20.50 The target may be unsupported, or you may not have
 0:20.50 a rust std library for that target installed. Try:
 0:20.50 
 0:20.50   rustup target add x86_64-unknown-linux-musl
 0:20.50 
```

**Comment by g3ngr33n** [comment]
The ebuild work fine in my side despite 1 warning and 1 error of a crate, I haven't yet emerge firefox but will do it asap

**Comment by smaeul** [comment]
Yes, I think editing `rust_target` to immediately return `host_or_target` will work.

**Comment by g3ngr33n** [comment]
I close this issue since the provided ebuild by smaeul work as expected.
