### ISSUE TITLE
iproute2 4.20.0 issue

### ISSUE THREAD

**Issue by g3ngr33n** [gentoo/musl#239]
>  * Applying iproute2-3.1.0-mtu.patch ...                                                                                                         [ ok ]
>  * Applying iproute2-4.20.0-configure-nomagic.patch ...                                                                                          [ ok ]
>  * Applying iproute2-4.20.0-limits.patch ...                                                                                                     [ ok ]
>  * Applying iproute2-4.20.0-no-ipv6.patch ...
> /var/tmp/portage/sys-apps/iproute2-4.20.0/temp/environment: line 542: /var/tmp/portage/sys-apps/iproute2-4.20.0/files/iproute2-4.20.0-no-ipv6.patch: No such file or directory     

  
Either the patch no-ipv6 is missing for this version or it should be removed from the ebuild. As I'm unsure which one is correct...

Thanks,

**Comment by anarchpenguin** [comment]
Your musl overlay is obviously out of date, the ebuild in the overlay is fine and does not include the patch.
