### ISSUE TITLE
global split-usr flag for the overlay

### ISSUE THREAD

**Issue by stefson** [gentoo/musl#246]
this was enabled via profiles yesterday, so it seems, and I wonder if there's any work which needs to be done for the overlay? Right now, all affected packages from the main tree have been pulled in on my musl system, but those from the overlay haven't, for instance `sys-libs/pam`

**Comment by blueness** [comment]
why was `sys-libs/pam` not pulled in?

**Comment by stefson** [comment]
Because it's pulled from the overlay, and that specific ebuild doesn't have the `split-usr` code yet. I honstly don't even know why this was introduced, neither what the consequences for the overlay are.

**Comment by stefson** [comment]
I opened a pullrequest for this, if there's a package I missed just ping me.

**Comment by blueness** [comment]
i don't know if you missed any.  how would we find out?

**Comment by stefson** [comment]
I'm confident to have gotten them all from @system and those I import from the overlay for my system. But there's one package I'm uncertain: `sys-libs/musl` itself. Could you evaluate wether the eclass needs to be imported? `sys-libs/glibc` has it - still not really sure why though.

**Comment by blueness** [comment]
No.  musl profiles were always no SYMLINK_LIB.

**Comment by stefson** [comment]
I took this commit for reference: https://github.com/gentoo/gentoo/pull/12446/commits/a56b4f1ca06d3b35274505f99fc2b847e3966314

According to it, only thing left is `sys-apps/audit`

**Comment by stefson** [comment]
closing as fixed, thanks pushing! :)

**Comment by blueness** [comment]
I'm sorry, I had to back out of this.  This is not the way to fix it.

**Comment by stefson** [comment]
what happened?

**Comment by blueness** [comment]
actually not this one, i but the strip flags.
