### ISSUE TITLE
net-firewall/nftables doesn't compile with sys-kernel/linux-headers::musl

### ISSUE THREAD

**Issue by trilean** [gentoo/musl#247]
Hi,

nftables doesn't compile with the patched headers from the musl overlay. I had to install the ones from ::gentoo to get it to build:

```
In file included from rule.c:35:
/usr/include/linux/if.h:82:2: error: expected identifier before numeric constant
  IFF_UP    = 1<<0,  /* sysfs */
  ^~~~~~
In file included from /usr/include/linux/if_pppox.h:25,
                 from ../include/linux/netfilter_bridge.h:10,
                 from rule.c:36:
/usr/include/linux/if.h:192:8: error: redefinition of 'struct ifmap'
 struct ifmap {
        ^~~~~
In file included from rule.c:35:
/usr/include/net/if.h:64:8: note: originally defined here
 struct ifmap {
        ^~~~~
In file included from /usr/include/linux/if_pppox.h:25,
                 from ../include/linux/netfilter_bridge.h:10,
                 from rule.c:36:
/usr/include/linux/if.h:229:8: error: redefinition of 'struct ifreq'
 struct ifreq {
        ^~~~~
In file included from rule.c:35:
/usr/include/net/if.h:76:8: note: originally defined here
 struct ifreq {
        ^~~~~
In file included from /usr/include/linux/if_pppox.h:25,
                 from ../include/linux/netfilter_bridge.h:10,
                 from rule.c:36:
/usr/include/linux/if.h:281:8: error: redefinition of 'struct ifconf'
 struct ifconf  {
        ^~~~~~
In file included from rule.c:35:
/usr/include/net/if.h:116:8: note: originally defined here
 struct ifconf {
        ^~~~~~
```
I tried with linux-headers 4.19/5.1 and even 5.2 with the patches from the musl overlay applied.

**Comment by blueness** [comment]
unfortunately with the headers from ::gentoo, other packages like `iptables` don't compile.  is it the same error for all the different version of the headers in ::musl?

**Comment by trilean** [comment]
Yes, I tried from the musl overlay: 4.19, 4.20, 5.1 as well as 5.2 with the patches for 5.1 from ::musl.
I temporarily install the headers from ::gentoo and built `nftables` against those so it's just an annoyance for me. Still, can we leave this bug open until this is properly fixed?

**Comment by anarchpenguin** [comment]
I have actually been doing some major testing with linux0headers-5.3::gentoo headers and have not had any problems. Upstream is even suggesting that we shouldn't have to patch current headers. I did apply a single patch to linux-headers-5.3::gentoo but that just works around a glibc hack that was added many moons ago, refer to patch libc-5.1-remove-sysinfo_h-from-kernel_h.patch in musl overlay
