### ISSUE TITLE
Update qtwebengine to 5.11.4

### ISSUE THREAD

**Issue by Jimmyb1126** [gentoo/musl#259]
Only 5.11.3 is available in the repo at the moment.

**Comment by blueness** [comment]
This looks like a bugger of an ebuild to bump.  Do you want to give it a go and make a pull request.

**Comment by Jimmyb1126** [comment]
> 
> 
> This looks like a bugger of an ebuild to bump. Do you want to give it a go and make a pull request.

I don't really have any experience with updating repos. If you don't think anyone else will do it anytime soon can you give me some pointers on the steps I would take to do it myself?

**Comment by blueness** [comment]
I'll see if I have time tomorrow.

**Comment by Jimmyb1126** [comment]
any updates on this?

**Comment by blueness** [comment]
There were a lot of mismatches in the patches and I don't have the time to
clean that up.  I think we may need to "start over".  Can you look at
alpine linux's patchset for this package.  Past back here what you find and
i'll try to incorporate them into the ebuild.

**Comment by Jimmyb1126** [comment]
Here's the Alpine patchset. I don't see any of these in our patchset.
https://git.alpinelinux.org/aports/tree/community/qt5-qtwebengine

It seems like a lot of glibc users are having issues with this version as well. You might find these helpful but I couldn't get their solutions to work without any musl patches.
https://forums.gentoo.org/viewtopic-t-1100872.html
https://forums.gentoo.org/viewtopic-t-1100926.html

**Comment by g3ngr33n** [comment]
I'm interested on qtwebengine, I could made the ebuild, but as long it has dbus as hard dependency... 

> I don't really have any experience with updating repos. If you don't think anyone else will do it anytime soon can you give me some pointers on the steps I would take to do it myself?

Was like that too, I wanted a ebuild for musl not available, perseverance is the mother of success

1 - Make your own overlay : https://wiki.gentoo.org/wiki/Layman 
2 - Start making custom patch  : https://wiki.gentoo.org/wiki/Patches
3 - Use repoman to check your ebuild https://wiki.gentoo.org/wiki/Repoman
