### ISSUE TITLE
Chromium, Opera and Firefox browsers not listed

### ISSUE THREAD

**Issue by Sharrisii** [gentoo/musl#262]
I don't see any of following browsers listed in the overlay:
* Chromium
* Opera
* Firefox
Having an easy way to compile these (ebuild scripts) under musl would be quite valuable (I very much doubt the official packages allow for compiling under musl by simply altering a setting in the script). Of firefox, I know it's compileable under musl (but it requires a lot of research so would be easier with a script); of the others I don't know whether they can be compiled under musl well (under chromium, it was possible, but I heard it can be quite unstable -see https://www.openwall.com/lists/musl/2016/03/18/20  -) and it certainly would be made a lot easier using an ebuild script.

Here's an old ebuild script for firefox musl which might be of use:
https://github.com/jakeogh/gentoo-musl-overlay/blob/master/www-client/firefox/firefox-41.0.2-r99.ebuild

Here's an ebuild script for chromium musl which might be of use:
https://github.com/smaeul/portage-overlay/blob/master/www-client/chromium/chromium-75.0.3770.100.ebuild

**Comment by blueness** [comment]
At this point, I don't have time to work on these.  However, if you want to open pull requests for ebuilds that you've written/found and that you've tested and know work, then please do so and we'll review them.

**Comment by smaeul** [comment]
@Sharrisii the firefox ebuild you linked is severely out of date. As far as I know, the only patch/change needed for current firefox is fixing the rust target name. If we need an ebuild in this overlay for that, it should be based off the current version in [the upstream portage tree](https://github.com/gentoo/gentoo).

I can submit my chromium ebuild here, but it has some non-musl-related changes in it as well. I'd rather not try to maintain two versions of it (one in my overlay and one with the minor customizations removed).

**Comment by Sharrisii** [comment]
Hey smaeul,
For me personally, just having a script just for chromium would already be more then sufficient really. Also, I'm not entirely sure whether we really need an overlay for the browsers at all ? Couldn't you just integrate the lines for compiling chromium with musl (i.e. line 113, 163-183, 594-597 of https://github.com/smaeul/portage-overlay/blob/master/www-client/chromium/chromium-75.0.3770.100.ebuild) into the upstream chromium ebuild (https://github.com/gentoo/gentoo/blob/master/www-client/chromium/chromium-78.0.3887.7.ebuild ) ?
Compiling with or without musl can then either be done manually (in script) or by using some sort of "musl" compilation flag.

Benefits then is that you don't need to maintain it (the gentoo community will do it), and you'll get a more updated version of the browser too (v78 rather then v75).

A same method could perhaps be used for the upstream firefox (rust target name fix), triggered by a "musl" compilation flag but as said, for me personally, just having chromium to compile easily under musl is already enough.
