### ISSUE TITLE
sys-apps/net-tools-1.60_p20161110235919::musl build fails

### ISSUE THREAD

**Issue by malinowsk-i** [gentoo/musl#28]
Hiya,

I'm just trying to emerge net-tools into a new stage 3 musl install (on ~amd64 globally) and it's failing to build with both clang and gcc. I can't quite piece together why it's doing so ;)

Here is the build log: https://bpaste.net/show/39b6cf916f03

And here is are my compile settings: https://bpaste.net/show/b3f686edf50b

I'm using libressl as well if that helps - Cheers!

**Comment by lluixhi** [comment]
Hm. You're using linux-headers from the gentoo repository.

Can you switch to the version from the musl repository?

`emerge -1 linux-headers::musl`

**Comment by malinowsk-i** [comment]
Heya, 

A bit busy at the mo - but thanks for the heads up; I'll try this and report back!

**Comment by blueness** [comment]
reopen this issue if you still have problems.
