### ISSUE TITLE
app-admin/hardinfo-0.5.2_pre20130823:0/0::musl build error

### ISSUE THREAD

**Issue by wftillman** [gentoo/musl#286]
emerge --jobs=1 =app-admin/hardinfo-0.5.2_pre20130823::musl
Calculating dependencies... done!

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) app-admin/hardinfo-0.5.2_pre20130823::musl
 * hardinfo-0.5.2_pre20130823.tar.xz BLAKE2B SHA512 size ;-) ...                                   [ ok ]
>>> Unpacking source...
>>> Unpacking hardinfo-0.5.2_pre20130823.tar.xz to /var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/work
>>> Source unpacked in /var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/work
>>> Preparing source in /var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/work/hardinfo-0.5.2_pre20130823 ...
 * Applying hardinfo-musl.patch ...

 * Failed Patch: hardinfo-musl.patch !
 *  ( /var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/files/hardinfo-musl.patch )
 *
 * Include in your bugreport the contents of:
 *
 *   /var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/temp/hardinfo-musl.patch.out

 * ERROR: app-admin/hardinfo-0.5.2_pre20130823::musl failed (prepare phase):
 *   Failed Patch: hardinfo-musl.patch!
 *
 * Call stack:
 *     ebuild.sh, line  125:  Called src_prepare
 *   environment, line 2725:  Called cmake-utils_src_prepare
 *   environment, line  900:  Called epatch '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/files/hardinfo-musl.patch'
 *   environment, line 1326:  Called die
 * The specific snippet of code:
 *               die "Failed Patch: ${patchname}!";
 *
 * If you need support, post the output of `emerge --info '=app-admin/hardinfo-0.5.2_pre20130823::musl'`,
 * the complete build log and the output of `emerge -pqv '=app-admin/hardinfo-0.5.2_pre20130823::musl'`.
 * The complete build log is located at '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/temp/environment'.
 * Working directory: '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/work/hardinfo-0.5.2_pre20130823'
 * S: '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/work/hardinfo-0.5.2_pre20130823'

>>> Failed to emerge app-admin/hardinfo-0.5.2_pre20130823, Log file:

>>>  '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/temp/build.log'

 * Messages for package app-admin/hardinfo-0.5.2_pre20130823:

 * Failed Patch: hardinfo-musl.patch !
 *  ( /var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/files/hardinfo-musl.patch )
 *
 * Include in your bugreport the contents of:
 *
 *   /var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/temp/hardinfo-musl.patch.out
 * ERROR: app-admin/hardinfo-0.5.2_pre20130823::musl failed (prepare phase):
 *   Failed Patch: hardinfo-musl.patch!
 *
 * Call stack:
 *     ebuild.sh, line  125:  Called src_prepare
 *   environment, line 2725:  Called cmake-utils_src_prepare
 *   environment, line  900:  Called epatch '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/files/hardinfo-musl.patch'
 *   environment, line 1326:  Called die
 * The specific snippet of code:
 *               die "Failed Patch: ${patchname}!";
 *
 * If you need support, post the output of `emerge --info '=app-admin/hardinfo-0.5.2_pre20130823::musl'`,
 * the complete build log and the output of `emerge -pqv '=app-admin/hardinfo-0.5.2_pre20130823::musl'`.
 * The complete build log is located at '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/temp/environment'.
 * Working directory: '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/work/hardinfo-0.5.2_pre20130823'
 * S: '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/work/hardinfo-0.5.2_pre20130823'
 *
 * The following package has failed to build, install, or execute postinst:
 *
 *  (app-admin/hardinfo-0.5.2_pre20130823:0/0::musl, ebuild scheduled for merge), Log file:
 *   '/var/tmp/portage/app-admin/hardinfo-0.5.2_pre20130823/temp/build.log'

**Comment by anarchpenguin** [comment]
Please sync and retest, I went ahead and rebased patch and tested. Please close both issues as I am unable to do so at the moment.

**Comment by wftillman** [comment]
Yes Sir,
Thank You for the assistance.

**Comment by anarchpenguin** [comment]
Already resolved closing.

**Comment by wftillman** [comment]
Thank You for Your response
