### ISSUE TITLE
dev-lang/luajit does not create library symlink

### ISSUE THREAD

**Issue by wylfen** [gentoo/musl#293]
As already mentioned in https://github.com/gentoo/musl/issues/224#issuecomment-480610407, dev-lang/luajit does not create library symlinks as it depends unconditionally on `ldconfig -n` in its Makefile.

Reported upstream @ https://github.com/LuaJIT/LuaJIT/issues/552

**Comment by anarchpenguin** [comment]
https://github.com/LuaJIT/LuaJIT/commit/18c9cf7d3788a8f7408df45df92fc4ae3bcc0d80 As upstream has fixed it, open a gentoo bug report and ask that the patch be included in ::gentoo

**Comment by wylfen** [comment]
Reported and [fixed](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=5f5a0bb3c9c316e21701d998d39eeec2fe3ac683).
