### ISSUE TITLE
ppc64 porting process tracker

### ISSUE THREAD

**Issue by gyakovlev** [gentoo/musl#295]
# general ppc64 problems we gonna deal with

ppc64 big endian variant will have some rough edges, just wanted to start an issue for tracking here:
## musl is elfv2 only on both ppc64 endians
* [MASKED] openssl assumes `ELFv1` abi if built with `USE=asm`, perlasm needs some fixes from https://github.com/openssl/openssl/pull/8883 , good part is that it's in master already but we may need downstream patches for a while or package.use.mask `asm` useflag for openssl.

* FIXED: gcc now builds correctly on big endian after I fixed it in https://github.com/gentoo/gentoo/commit/5136179f9356f0bcb34fa5b8c5d0d0817f316ec9#diff-0bea9a8afc6119e4d3db30d8ddbc3d64
upstream bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93157

* llvm, as gcc, assumes `ELFv1` abi on big endian ppc64, but unlike gcc it's impossible to modify at compile time as abi is derived from host triple. it needs patches.

will add more issues as I do stage/catalyst/world builds.

**Comment by mjeveritt** [comment]
Anything new here?

**Comment by gyakovlev** [comment]
quite a bit actually, forgot I was going to update this one.

ok here's current situation:
* Last week I've rebuilt both my `ppc64` and `ppc64le` musl stages, not a single build failure (stage3 packages).
* for openssl[asm] on `ppc64be-musl-elfvabi2` version 2(currently alpha) contains a fix, mask remains for now.
* gcc need extra patches for multilib libdir (still shows lib64) https://github.com/gentoo/musl/issues/233#issuecomment-580147361,
i found files to patch, will update musl overlay gcc pure-64 patch as time permits. it's a pre-requisite for shipping stages.
* musl catalyst needs to be enabled, pr opened here: https://github.com/gentoo/releng/pull/5 , idk how behind it is, need to re-check.
* almost ready to enable `ppc64be` profiles as there are no stage3 failures. profile required to enable catalyst builds.
* bonus: both ppc64 gentoo machines now have le and be volatile chroots with musl, so developers with access can use them to test stuff, I maintain both of 'em. ppc64be_musl_elfvabi2 is the most picky one, really good for testing portability.

**Comment by gyakovlev** [comment]
first ppc64le-musl-hardened stage released:
https://gentoo.osuosl.org/releases/ppc/autobuilds/current-stage3-ppc64le-musl-hardened/

be coming next, soon.
after be is done I may poke ppc32 one again, seems nobody done it yet.

**Comment by gyakovlev** [comment]
clang/llvm-10.0.1 and up contain proper fix for elfv2eabi on musl by default.
https://reviews.llvm.org/D72352

**Comment by gyakovlev** [comment]
first big-endian musl ppc64 stage3 shipped:
https://gentoo.osuosl.org/releases/ppc/autobuilds/current-stage3-ppc64-musl-hardened

it should just work from on now, I did not observe breakage in stage3 builds for a long time since problematic packages got masked/patched.

so, DONE!
I've joined `releng` and will look after those builds from on now.
