### ISSUE TITLE
sys-libs/ldb: please update

### ISSUE THREAD

**Issue by stintel** [gentoo/musl#298]
sys-libs/ldb-2.0.8 was marked stable in Gentoo and is now preferred over 1.3.6 from the overlay. Please update.

**Comment by blueness** [comment]
i pushed with stable keywords.  please test and let me know asap if anything is wrong.

**Comment by stintel** [comment]
Thanks, seems to build fine. Unfortunately samba was also bumped in Gentoo and that also does not compile. Is it preferred to create an issue here, or in the Gentoo bugtracker?

**Comment by blueness** [comment]
Create issues here.  Usually I'm  a lot faster (or one of the other devs) but things are crazy right now.
