### ISSUE TITLE
ERROR: sys-libs/ldb-2.0.8::musl failed (compile phase)

### ISSUE THREAD

**Issue by stintel** [gentoo/musl#305]
[build.log](https://github.com/gentoo/musl/files/4489568/build.log)

**Comment by anarchpenguin** [comment]
> [build.log](https://github.com/gentoo/musl/files/4489568/build.log)

Your missing pid_t support, this is caused from this missing fcntl.h not being included when it should have been.

**Comment by mjeveritt** [comment]
Is there a Gentoo bug filed?

**Comment by stintel** [comment]
> Is there a Gentoo bug filed?

No. See https://github.com/gentoo/musl/issues/298#issuecomment-602256833
