### ISSUE TITLE
sys-libs/libunwind fails on aarch64

### ISSUE THREAD

**Issue by shawnanastasio** [gentoo/musl#339]
libunwind fails to build on aarch64:
```
src/mi/Gfind_dynamic_proc_info.c:26:
/var/tmp/portage/sys-libs/libunwind-1.4.0/work/libunwind-1.4.0/include/libunwind-aarch64.h:195:2: error: unknown type name '__sigset_t'
  195 |  __sigset_t uc_sigmask;
      | 
```

This is fixed with the following patch from Void Linux: https://github.com/void-linux/void-packages/raw/master/srcpkgs/libunwind/patches/aarch64-musl.patch (modified to apply with -p1 instead of -p0):

```
--- a/include/libunwind-aarch64.h
+++ b/include/libunwind-aarch64.h
@@ -192,7 +192,7 @@
 	unsigned long uc_flags;
 	struct ucontext *uc_link;
 	stack_t uc_stack;
-	__sigset_t uc_sigmask;
+	sigset_t uc_sigmask;
 	struct unw_sigcontext uc_mcontext;
   } unw_tdep_context_t;
```

**Comment by anarchpenguin** [comment]
Create a proper patch using git and send it upstream. Also open a proper pull request to have it landed in the musl overlay.

**Comment by anarchpenguin** [comment]
https://github.com/libunwind/libunwind/commit/5df1555828add4e256cb4bba49fffffc22127c34#diff-cf27614168d726ca3141e52777897660d3859bc81c4e8fce288a9632c91556d7

File a bug report with package maintainer and ask to have the patch backported for current ebuilds.
