### ISSUE TITLE
sys-boot/efibootmgr fails to build

### ISSUE THREAD

**Issue by Keepco** [gentoo/musl#34]
Hello,
building efibootmgr fails:
```
In file included from /usr/include/stdlib.h:19:0,
                 from unparse_path.c:26:
/usr/include/bits/alltypes.h:18:13: error: conflicting types for ‘wchar_t’
 typedef int wchar_t;
             ^
In file included from unparse_path.c:24:0:
/usr/lib/gcc/x86_64-gentoo-linux-musl/4.9.4/include/stddef.h:324:24: note: previous declaration of ‘wchar_t’ was here
 typedef __WCHAR_TYPE__ wchar_t;
```

However, removing `-fshort-wchar` from Make.defaults fixes it (basically the same thing as https://cgit.gentoo.org/proj/musl.git/tree/sys-libs/efivar/files/0.21-musl.patch?id=72d39834f513ed0ec6d4c3030f8bce402e71d236)

**Comment by blueness** [comment]
looks good to me, do you want to prepare a pull request?

**Comment by Keepco** [comment]
Sure, I'll create one

**Comment by lluixhi** [comment]
Huh. I've been using GCC-6.3.0 for a while so I haven't come across this, maybe it's just a bug in GCC lower than 5.x?

**Comment by Keepco** [comment]
Possibly, I currently set up a stage3 with musl, so I didn't have the time to upgrade to GCC >4.9.4 yet. I'll test it tomorrow

**Comment by blueness** [comment]
i'm keeping the stage3's as close to gentoo stable as possible.  it'll be a while before gcc-6 is stable.

**Comment by Keepco** [comment]
Took me some time, but I just tried it with GCC 6.3.0 and it indeed builds. GCC 6.3.0 actually seens to make multiple packages work with -fshort-wchar, like example edk2-ovmf

**Comment by lluixhi** [comment]
Interesting -- in GCC 6.3.0, in `stddef.h` are the lines:
```
#ifndef __WCHAR_TYPE__
#define __WCHAR_TYPE__ int
#endif
#ifndef __cplusplus
typedef __WCHAR_TYPE__ wchar_t;
#endif
```
So the definitions match up -- what is the type definition in 4.9.4?

If it's the same, I think 6.3.0 probably just got a bit more lenient with typedefs and is looking a bit further into the past before deciding there's a conflict.
