### ISSUE TITLE
dev-util/elfutils: Update patchset

### ISSUE THREAD

**Issue by ajakk** [gentoo/musl#340]
gentoo.git is now at elfutils-0.180, but this version is broken when building with musl. The musl-* patches from the ::musl version 0.178 also do not fix the issue completely.

**Comment by stefson** [comment]
it would help to sync the keywords of 0.178 , can you open a pullrequest?

**Comment by ajakk** [comment]
Sync from ::gentoo? 0.178 doesn't exist anymore there, it was removed in May:

```
commit f01a48eca1b21e236a457cdfb2745dea1256c318
Author: Sergei Trofimovich <slyfox@gentoo.org>
Date:   Sat May 2 18:44:30 2020 +0100

    dev-libs/elfutils: drop old

    Package-Manager: Portage-2.3.99, Repoman-2.3.22
    Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>

delete mode 100644 dev-libs/elfutils/elfutils-0.178.ebuild
```

**Comment by stefson** [comment]
well, I thought of 0.178 as a better alternative over 0.177, maybe it has some more bugfixes, but I didn't pay attention to the fact it has been deleted from the tree and maybe never was stable anyway. 

I don't have a solution but to stick with 0.177 for now.
