### ISSUE TITLE
sys-devel/binutils::gentoo is pulled into stage3

### ISSUE THREAD

**Issue by stefson** [gentoo/musl#343]
emerge -pv binutils
```
These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] sys-devel/binutils-2.33.1-r1:2.33::musl [2.33.1-r1:2.33::gentoo] USE="gold nls plugins -default-gold -doc -multitarget -static-libs -test" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

```

same as with sys-devel/gcc, only here it's less cpu cycles spent to switch back to ::musl

is this good, is this bad, shall it be fixed?

**Comment by anarchpenguin** [comment]
I can understand gcc being pulled as ::gentoo had the newer stable, as far as why binutils was used in the stage3 not sure yet. I am gonna do a bit of testing here later today to see what is going on.

**Comment by anarchpenguin** [comment]
Just to give you a heads up the ::musl package just sets the linker to 2MB for the stack so we do not segfault with pgo builds in mozilla projects.

**Comment by stefson** [comment]
Yes, I know that the only reason for the forked binutils ebuild is the greater stack size, so there's no real consequence here unless a user would go for lto and pgo stuff. With gcc, I'm not that certain. 

By the way, have you heard about https://bugs.gentoo.org/739612?

**Comment by stefson** [comment]
binutils has been removed from the overlay, closing.
