### ISSUE TITLE
musl stages occasionally ship with ::gentoo gcc

### ISSUE THREAD

**Issue by gyakovlev** [gentoo/musl#351]
I recently checked `stage3-amd64-musl-hardened-20201017.tar.bz2` and it has unpatched ::gentoo gcc in it.
afaik catalyst supports deleting files from package.use subdirectory, maybe it also supports package.mask?
stages should mask `sys-devel/gcc::gentoo` at build time and remove mask file before packing.

**Comment by mjeveritt** [comment]
At the risk of provoking devs, tagging @mattst88 for releng@ and @blueness as toolchain@ for addressing this.

**Comment by gyakovlev** [comment]
happened again recently with `ppc64` musl stage3, despite both `musl` and `gentoo` repos having the same version of gcc stable, but `::gentoo` version was preferred.

needs some kind of temporary mask file in catalyst portage config, imo, which can be cleaned up on tarball creation.

**Comment by gyakovlev** [comment]
new ppc64 musl stages now ship proper gcc

```shell-session
tar -x ./var/db/pkg -f stage3-ppc64le-musl-hardened-20210614T080607Z.tar.xz
cat var/db/pkg/sys-devel/gcc-10.2.0-r5/repository 
musl
```

**Comment by gyakovlev** [comment]
need other arches to implement https://github.com/gentoo/releng/commit/4d8b4d68504beb838ce2d2823e6489796e629842

**Comment by mjeveritt** [comment]
> need other arches to implement [gentoo/releng@4d8b4d6](https://github.com/gentoo/releng/commit/4d8b4d68504beb838ce2d2823e6489796e629842)

I think this is probably @akhuettel 's domain .. thanks Georgie for your work so far!

**Comment by gyakovlev** [comment]
> > need other arches to implement [gentoo/releng@4d8b4d6](https://github.com/gentoo/releng/commit/4d8b4d68504beb838ce2d2823e6489796e629842)
> 
> I think this is probably @akhuettel 's domain .. thanks Georgie for your work so far!

you are welcome Michał

**Comment by anarchpenguin** [comment]
::gentoo now supports musl in 11.2.x we no longer carry gcc in the overlay

**Comment by gyakovlev** [comment]
yeah let's close this one, it's solved.
