### ISSUE TITLE
x11-apps/igt-gpu-tools fail with gcc 10 

### ISSUE THREAD

**Issue by g3ngr33n** [gentoo/musl#355]
> FAILED: tools/intel_gpu_top 
> x86_64-gentoo-linux-musl-gcc  -o tools/intel_gpu_top tools/intel_gpu_top.p/intel_gpu_top.c.o -Wl,--as-needed -Wl,--no-undefined -O2 -pipe -Wl,-O1 -Wl,--as-needed -Wl,--start-group lib/libigt_perf.a -Wl,--end-group
> /usr/lib/gcc/x86_64-gentoo-linux-musl/10.2.0/../../../../x86_64-gentoo-linux-musl/bin/ld: lib/libigt_perf.a(igt_perf.c.o):(.bss+0x0): multiple definition of `igt_subtest_jmpbuf'; tools/intel_gpu_top.p/intel_gpu_top.c.o:(.bss+0x20): first defined here
> collect2: error: ld returned 1 exit status
> [114/319] /usr/lib/python-exec/python3.7/meson --internal vcstagger ../igt-gpu-tools-1.24/lib/version.h.in lib/version.h NO-GIT /var/tmp/portage/x11-apps/igt-gpu-tools-1.24/work/igt-gpu-tools-1.24/lib @VCS_TAG@ '(.*)' /usr/bin/git log -n1 --pretty=format:g%h
> fatal: not a git repository (or any of the parent directories): .git
> ninja: build stopped: subcommand failed.
>

**Comment by anarchpenguin** [comment]
This needs to be bumped and fixed for latest stable release.

**Comment by g3ngr33n** [comment]
https://github.com/gentoo/musl/pull/357

Feel free to close this issue
