### ISSUE TITLE
Fail icedtea-bin alpine binary download

### ISSUE THREAD

**Issue by lobzmedunimes** [gentoo/musl#356]
dev-java/icedtea-bin-3.16.0 fail to download apk, that's because there is a double dash on URL, to fix this, remove dash on BASE_URI="http://dl-cdn.alpinelinux.org/alpine/edge/community  ""/""

get_apk_names() {
	ARCH="${2-${1}}"
	echo "${1}? (
		${BASE_URI}/${ARCH}/${ALPINE_PN}-${ALPINE_PV}.apk -> ${P}-${ARCH}.tar.gz
		${BASE_URI}/${ARCH}/${ALPINE_PN}-jre-${ALPINE_PV}.apk -> ${P}-jre-${ARCH}.tar.gz
		${BASE_URI}/${ARCH}/${ALPINE_PN}-jre-base-${ALPINE_PV}.apk -> ${P}-jre-base-${ARCH}.tar.gz
		${BASE_URI}/${ARCH}/${ALPINE_PN}-jre-lib-${ALPINE_PV}.apk -> ${P}-jre-lib-${ARCH}.tar.gz
		${BASE_URI}/${ARCH}/${ALPINE_PN}-doc-${ALPINE_PV}.apk -> ${P}-doc-${ARCH}.tar.gz
		examples? ( ${BASE_URI}/${ARCH}/${ALPINE_PN}-demos-${ALPINE_PV}.apk -> ${P}-demos-${ARCH}.tar.gz )
		debug? ( ${BASE_URI}/${ARCH}/${ALPINE_PN}-dbg-${ALPINE_PV}.apk -> ${P}-dbg-${ARCH}.tar.gz )
	)"
}

DESCRIPTION="Binary build of the IcedTea JDK from Alpine Linux"
HOMEPAGE="http://icedtea.classpath.org"
BASE_URI="http://dl-cdn.alpinelinux.org/alpine/edge/community/"
SRC_URI="
	$(get_apk_names amd64 x86_64)
	$(get_apk_names arm armhf)
	$(get_apk_names arm armv7)
	$(get_apk_names arm64 aarch64)
	$(get_apk_names ppc64 ppc64le)
	$(get_apk_names s390 s390x)
	$(get_apk_names x86 x86)

**Comment by mjeveritt** [comment]
Please can you formulate a diff/patch or pull-request so it is apparent exactly where the changes occur? Thanks!
