### ISSUE TITLE
app-emulation/qemu-2.8.0-r7 broken

### ISSUE THREAD

**Issue by parazyd** [gentoo/musl#36]
The ebuild for app-emulation/qemu-2.8.0-r7 is broken because there is a missing file. It tries to generate an init script by concatenating files, but they are missing.

https://github.com/gentoo/musl/blob/master/app-emulation/qemu/qemu-2.8.0-r7.ebuild#L625

**Comment by lluixhi** [comment]
Whoops. I should've double-checked that last time I bumped it.
