### ISSUE TITLE
net-misc/networkmanager-1.26.4::musl failed (configure phase) - configure: error: "couldn't find pppd.h. pppd development headers are required."

### ISSUE THREAD

**Issue by ernsteiswuerfel** [gentoo/musl#369]
net-dialup/ppp-2.4.7-r3::musl builds fine but networkmanager won't pick it up.
[networkmanager-1.26.4:20210105-101008.log](https://github.com/gentoo/musl/files/5769504/networkmanager-1.26.4.20210105-101008.log)
```
[...]
checking pppd/pppd.h usability... no
checking pppd/pppd.h presence... no
checking for pppd/pppd.h... no
configure: error: "couldn't find pppd.h. pppd development headers are required."

!!! Please attach the following file when seeking support:
!!! /var/tmp/portage/net-misc/networkmanager-1.26.4/work/NetworkManager-1.26.4-abi_x86_64.amd64/config.log
 * ERROR: net-misc/networkmanager-1.26.4::musl failed (configure phase):
 *   econf failed
```

**Comment by anarchpenguin** [comment]
This is not just a musl issue, it will also be effecting ::gentoo tree as well. I am willing to check and see if ppp can be updated.

**Comment by mjeveritt** [comment]
@Polynomial-C and I have been working a bit with ppp upstream on merging Gentoo patches, so we'll flag this up, and see if we can get it fixed properly.

**Comment by gyakovlev** [comment]
obsolete with https://github.com/gentoo/musl/commit/d1dd81b40c23b1b6451a95e269394adccfbd81cc ?

**Comment by mjeveritt** [comment]
> obsolete with [d1dd81b](https://github.com/gentoo/musl/commit/d1dd81b40c23b1b6451a95e269394adccfbd81cc) ?

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/1.30.0/NEWS#L11 only states musl compatibility . We probably need to check out what the situation with net-dialup/ppp is, before we can close this.

**Comment by mjeveritt** [comment]
That said, d8cd9e109f8a80cede2bafc34d12744230b31072 looks like it should cover this issue, although I don't have sufficient info to verify this ..

**Comment by anarchpenguin** [comment]
Is anyone able to still confirm this with current stable which is 1.30.4?

**Comment by ernsteiswuerfel** [comment]
Yes I am still seeing this.
```
checking pppd/pppd.h usability... no
checking pppd/pppd.h presence... no
checking for pppd/pppd.h... no
configure: error: "couldn't find pppd.h. pppd development headers are required."

!!! Please attach the following file when seeking support:
!!! /var/tmp/portage/net-misc/networkmanager-1.30.4/work/NetworkManager-1.30.4-abi_x86_64.amd64/config.log
 * ERROR: net-misc/networkmanager-1.30.4::gentoo failed (configure phase):
 *   econf failed
```
[config.log](https://github.com/gentoo/musl/files/6598440/config.log)

**Comment by mjeveritt** [comment]
Hmm this looks the same as https://bugs.gentoo.org/713392 and https://bugs.gentoo.org/713466 whatever it is ... seems to be musl-specific ..

**Comment by mjeveritt** [comment]
@ernsteiswuerfel - your build log looks like it may still refer to net-dialup/ppp::musl where I do see https://gitweb.gentoo.org/proj/musl.git/commit/?id=d8cd9e109f8a80cede2bafc34d12744230b31072 removed it - just checking whether we have a problem with ::gentoo version of ppp also, potentially?

_either that or I've accidentally cross-referenced something I shouldn't have.._

**Comment by ernsteiswuerfel** [comment]
@mjeveritt Nope, this time `net-dialup/ppp-2.4.9-r2:0/2.4.9::gentoo` was pulled in and used.

**Comment by gyakovlev** [comment]
```
configure:24629: checking pppd/pppd.h presence
configure:24629: x86_64-gentoo-linux-musl-gcc -E  conftest.c
In file included from conftest.c:68:
/usr/include/pppd/pppd.h:60:10: fatal error: net/ppp_defs.h: No such file or directory
   60 | #include <net/ppp_defs.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
configure:24629: $? = 1
```

the uapi version is installed at:
`sys-kernel/linux-headers: /usr/include/linux/ppp_defs.h`


As I see, openembedded and alpine install ppp's version of `net/ppp_defs.h` to `/usr/include/net/ppp_defs.h`

https://git.alpinelinux.org/aports/plain/main/ppp/APKBUILD
https://patchwork.openembedded.org/patch/150397/

maybe gentoo's version should do the same behind `use elibc_musl` ?

**Comment by mjeveritt** [comment]
Yes, I queried the #musl support channel, and the suggestion was to adopt a similar strategy to alpine's 'ppp-dev' subpackage which installs the header as described.

**Comment by anarchpenguin** [comment]
> Yes I am still seeing this.
> 
> ```
> checking pppd/pppd.h usability... no
> checking pppd/pppd.h presence... no
> checking for pppd/pppd.h... no
> configure: error: "couldn't find pppd.h. pppd development headers are required."
> 
> !!! Please attach the following file when seeking support:
> !!! /var/tmp/portage/net-misc/networkmanager-1.30.4/work/NetworkManager-1.30.4-abi_x86_64.amd64/config.log
>  * ERROR: net-misc/networkmanager-1.30.4::gentoo failed (configure phase):
>  *   econf failed
> ```
> 
> [config.log](https://github.com/gentoo/musl/files/6598440/config.log)

As you can confirm it using that provided by ::gentoo I suggest opening a bug report. This is no longer a musl specific issue but an issue for anyone using ppp still.

**Comment by ernsteiswuerfel** [comment]
Done. See: https://bugs.gentoo.org/794982

Closing here.
