### ISSUE TITLE
sys-apps/groff-1.2.2.4::musl not installing alongside app-text/opensp-1.5.2-r6::gentoo

### ISSUE THREAD

**Issue by BeanieBen9990** [gentoo/musl#370]
I'm installing gentoo-musl for the first time, and I've added the musl overlay to make sure it works. During the first @world set emerge, everything was going pretty smooth until it tried to install groff, when it was blocked. /usr/lib/charset.alias was owned by opensp, and couldn't be installed alongside groff, so I couldn't finish emerging groff. I'm going to try to use groff from the gentoo overlay, and if that doesn't work, I'll try an old version of opensp, as long as it doesn't cause any package dependencies to go awry.

**Comment by BeanieBen9990** [comment]
I disabled the nls use flag for opensp and it allowed groff to be installed. Opensp then was unable to be emerged once it was enabled again, so I left it disabled. Should I not use the nls use flag overall, or is this an ok fix?

**Comment by mjeveritt** [comment]
You're clearly not using the correct musl profile, as it masks off the install of 'charset.alias' completely.
Check 'eselect profile list' to pick the correct profile for your arch/setup.

This is not a bug/issue :smiley:

**Comment by BeanieBen9990** [comment]
No I definitely am using the right profile. 31 (default/linux/amd64/17.0/musl) I have a current installation of gentoo with glibc I had copied by make.conf from if that would make a difference. I don't think any other files from my current install were copied over.

**Comment by mjeveritt** [comment]
This is the setting which masks that file from ever being installed (if its 'leftover' I can't vouch for the outcome .. probably nothing will remove it again) - https://gitweb.gentoo.org/repo/gentoo.git/tree/profiles/features/musl/make.defaults#n18

**Comment by mjeveritt** [comment]
> This is the setting which masks that file from ever being installed (if its 'leftover' I can't vouch for the outcome .. probably nothing will remove it again) - https://gitweb.gentoo.org/repo/gentoo.git/tree/profiles/features/musl/make.defaults#n18

that said, if you override INSTALL_MASK (which I did) it's not a 'cumulative' variable in make.conf - you -will- need to append to it ie. ```INSTALL_MARK="${INSTALL MASK} <new stuff>"```

**Comment by BeanieBen9990** [comment]
thanks! added that stuff to my make.conf :)
