### ISSUE TITLE
There's a couple patches I've found that make rust compile that I'd love to see tested

### ISSUE THREAD

**Issue by BeanieBen9990** [gentoo/musl#371]
I've found a couple of patches around that fix rust compiling on my musl system. I've compiled spidermonkey with just one patch to the ebuild, just changing the target to x86_64-unknown-linux-musl from x86_64-gentoo-linux-musl, because rust compiled with only that target. However, if rust was able to compile with x86_64-gentoo-linux-musl, then spidermonkey would need no configuring or patching. Firefox compiled with no changes or patches from portage. This would be an amazing addition to musl on gentoo and even possibly other systems if it could be added and tested.

**Comment by mjeveritt** [comment]
Best place for rust support is https://github.com/smaeul/portage-overlay/tree/master/dev-lang/rust .
I suspect @smaeul himself might be able to comment further, but his overlay is recommended for rust/firefox on musl systems.

**Comment by BeanieBen9990** [comment]
Ah! That's not where I got mine! I'm glad more than one option is available! It looks like his version is on 1.47.0, however the one I'm running 1.48.0! Regardless I love seeing support being added and I hope a fix for rust gets added here soon.

**Comment by anarchpenguin** [comment]
> I've found a couple of patches around that fix rust compiling on my musl system. I've compiled spidermonkey with just one patch to the ebuild, just changing the target to x86_64-unknown-linux-musl from x86_64-gentoo-linux-musl, because rust compiled with only that target. However, if rust was able to compile with x86_64-gentoo-linux-musl, then spidermonkey would need no configuring or patching. Firefox compiled with no changes or patches from portage. This would be an amazing addition to musl on gentoo and even possibly other systems if it could be added and tested.

This issue does nothing as you have not included any information. If you want to see 1.48.0 added to the overlay you would need to create a PR with your suggested changes. Please feel free to reopen the issue if you want to continue with your work on rust support via the overlay.
