### ISSUE TITLE
dev-util/perf::gentoo doesn't build against musl

### ISSUE THREAD

**Issue by stintel** [gentoo/musl#378]
Happens due to PATH_MAX being undefined.

[build.log](https://github.com/gentoo/musl/files/6018023/build.log) from 5.8, same problem with .5.4.20 or 5.10.16.

Fix is simple, for 5.10.16, this works:
```
Index: tools/perf/util/get_current_dir_name.c
===================================================================
--- perf/util/get_current_dir_name.c
+++ perf/util/get_current_dir_name.c
@@ -3,6 +3,7 @@
 //
 #ifndef HAVE_GET_CURRENT_DIR_NAME
 #include "get_current_dir_name.h"
+#include <limits.h>
 #include <unistd.h>
 #include <stdlib.h>
 

```
(silly github doesn't support attaching .patch files 🤦🏻)

**Comment by mjeveritt** [comment]
Do we have a Gentoo bugzilla bug for this? can we link it here, please?! TIA

also, this is a common musl bug, so its a trivial fix, as you suggest.

**Comment by stintel** [comment]
> Do we have a Gentoo bugzilla bug for this? can we link it here, please?! TIA

No. I have been told in the past an issue here is enough.

**Comment by anarchpenguin** [comment]
> > Do we have a Gentoo bugzilla bug for this? can we link it here, please?! TIA
> 
> No. I have been told in the past an issue here is enough.

Open an bug, also file a bug with upstream.
