### ISSUE TITLE
Sync overlay with musl-extras

### ISSUE THREAD

**Issue by DmitryHetman** [gentoo/musl#4]
https://github.com/lluixhi/musl-extras
musl-extras has support for wayland, weston, chromium, gcc 6.1 and much more

**Comment by blueness** [comment]
I am aware of that overlay but I was waiting for lluixhi to prepare stuff for this overlay which is the official one.  Maybe you can bug him to get stuff moved over.

**Comment by DmitryHetman** [comment]
Ok.

**Comment by blueness** [comment]
Aric has access and will be moving stuff over.

**Comment by blueness** [comment]
this bug is done.
