### ISSUE TITLE
support SELinux (sys-apps/policycoreutils) with musl

### ISSUE THREAD

**Issue by alexminder** [gentoo/musl#45]
After recently news of  [Grsecurity: Passing the Baton](https://grsecurity.net/passing_the_baton.php) I choose to move from RBAC to Selinux.

I'm using `musl` profile:
```
# eselect profile list
Available profile symlink targets:
...
  [17]  hardened/linux/musl/amd64 *
...
```

I copy files from `/usr/portage/profiles/features/selinux/` to `/etc/portage/profile/` to get `selinux` profile with `musl`.

But when I try to rebuild world, I got dependancy from `glibc`:
```
The following mask changes are necessary to proceed:
 (see "package.unmask" in the portage(5) man page for more details)
# required by sys-apps/policycoreutils-2.6-r1::gentoo
# required by sec-policy/selinux-sasl-2.20170204-r2::gentoo
# required by dev-libs/cyrus-sasl-2.1.26-r9::gentoo
# required by mail-mta/exim-4.88::gentoo[sasl]
# required by @selected
# required by @world (argument)
# /usr/portage/profiles/hardened/linux/musl/package.mask:
=sys-libs/glibc-2.23-r3
```

I think `SELinux` must to work with `musl` because no other good MAC alternative exists.

**Comment by doughdemon** [comment]
Please try whether it works after removing the line from the ebuild mentioning glibc, and please file a bug on b.g.o.

**Comment by alexminder** [comment]
I tried - it does not works with musl.
I opened bug https://bugs.gentoo.org/show_bug.cgi?id=617704

**Comment by blueness** [comment]
Can you give me a list of packages that are needed for SELinux to work.  That bug looks like an easy fix.

**Comment by alexminder** [comment]
sys-apps/policycoreutils (This pkg is most important)
sys-libs/libsemanage
sys-process/audit (with USE=+python)

**Comment by lluixhi** [comment]
I can look into this.

**Comment by alexminder** [comment]
>I can look into this.

It would be great, because sys-libs/libsemanage with AlpineLinux patch have problems with connect login with SEUSER and HOMEDIR context.

**Comment by atlaua** [comment]
Someone (not me) has submitted musl compatibility patches to the audit and policycoreutils upstreams, so those problems should go away sooner or later. In the meantime, I've added patches to this overlay. I didn't address the sys-process/audit[python] issue, though, that's still broken. I'll have a look during the weekend.

**Comment by blueness** [comment]
@atlaua Thanks, there does seem to be a growing interest in selinux/musl.

**Comment by blueness** [comment]
okay i've added both an amd64 hardened/selinux profile and an x86 vanilla/selinux profile.  we're now officially supporting selinux + musl.
