### ISSUE TITLE
sys-libs/compiler-rt-sanitizers-4.0.0 musl patches

### ISSUE THREAD

**Issue by tamiko** [gentoo/musl#46]
Hi there,

I have successfully compiled compiler-rt-sanitizers on hardened/musl with the following patch [1].
Would be nice to push that to the overlay.

[1] https://gist.github.com/anonymous/92df175ea663004c5055bd6085476a70

**Comment by blueness** [comment]
That looks good enough to go upstream.  If you prepare a pull request against the overlay I'll push it.
