### ISSUE TITLE
sys-libs/pam-1.2.1 fails to compile: undefined reference to crypt

### ISSUE THREAD

**Issue by fusion809** [gentoo/musl#50]
Hi,

Tried to compile sys-libs/pam-1.2.1 (as part of running `emerge -uDU --with-bdeps=y @world` during initial system setup using a Stage3 tarball) and it returned: https://paste.pound-python.org/show/6PsAuc2MBgaC60wY4aL4/. My `emerge --info '=sys-libs/pam-1.2.1::musl'` output is https://paste.pound-python.org/show/CluNDBoMSzmfhME64B0Z/. `emerge -pqv '=sys-libs/pam-1.2.1::musl'` returns:

```bash
[ebuild   R   ] sys-libs/pam-1.2.1 [1.2.1] USE="cracklib nls pie -audit -berkdb* -debug -nis (-selinux) {-test} -vim-syntax" 
```

The exact error seems to be:

```bash
libtool: link: x86_64-pc-linux-gnu-gcc -shared  -fPIC -DPIC  .libs/pam_pwhistory.o .libs/opasswd.o   -Wl,-rpath -Wl,/var/tmp/portage/sys-libs/pam-1.2.1/work/Linux-PAM-1.2.1-abi_x86_64.amd64/libpam/.libs -Wl,--as-needed ../../libpam/.libs/libpam.so -ldl  -O2 -Wl,--version-script=/var/tmp/portage/sys-libs/pam-1.2.1/work/Linux-PAM-1.2.1/modules/pam_pwhistory/../modules.map -Wl,-O1 -Wl,--no-undefined -Wl,-O1   -Wl,-soname -Wl,pam_pwhistory.so -o .libs/pam_pwhistory.so
.libs/opasswd.o: In function `check_old_pass':
opasswd.c:(.text+0x278): undefined reference to `crypt'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:652: pam_pwhistory.la] Error 1
make[3]: Leaving directory '/var/tmp/portage/sys-libs/pam-1.2.1/work/Linux-PAM-1.2.1-abi_x86_64.amd64/modules/pam_pwhistory'
make[2]: *** [Makefile:422: all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/sys-libs/pam-1.2.1/work/Linux-PAM-1.2.1-abi_x86_64.amd64/modules'
make[1]: *** [Makefile:471: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/sys-libs/pam-1.2.1/work/Linux-PAM-1.2.1-abi_x86_64.amd64'
make: *** [Makefile:402: all] Error 2
```

if there's some info I can provide that I'm missing please tell me as I would like to get this compile error resolved.

Thanks for your time,
Brenton

**Comment by blueness** [comment]
I'm not ignoring this bug, I just can't reproduce and I don't understand it.  musl provides crypt() as can be easily verified by doing `readelf -sW /usr/lib/libc.so  | grep " crypt"`.  I waited a while to see if I would ever hit it, but I never did.  Sorry I can't help more.  If you have more information then reopen this bug, but without some clue, I can't see what's going wrong.
