### ISSUE TITLE
media-gfx/exiv2-0.26_p20171104 uses PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP

### ISSUE THREAD

**Issue by lluixhi** [gentoo/musl#51]
musl doesn't provide this because it isn't posix compliant and would require reliance on a certain kind of pthread structure.

At the moment I'm not sure how to fix this.

**Comment by parazyd** [comment]
It seems that `0.26_p20171013` from portage now compiles fine.

**Comment by lluixhi** [comment]
Thanks!
