### ISSUE TITLE
net-misc/openssh: builds with wtmp support

### ISSUE THREAD

**Issue by wylfen** [gentoo/musl#52]
Currently, openssh is built with wtmp support because the wtmp detection in ./configure is broken for musl-based systems. The program is in a working state, of course, but any auth log output will be polluted by `sshd[27660]: wtmp_write: problem writing /dev/null/wtmp: Not a directory`.

I propose adding `--disable-wtmp` to the openssh ebuild for this overlay.
See also [this bug](https://bugs.alpinelinux.org/issues/2744) for Alpine Linux.

**Comment by blueness** [comment]
i doubt people will want this in the main tree.  a better approach would be to fix configure.  did you look into that?

**Comment by vehk** [comment]
I have not, although that sounds like a better idea indeed. I know for a fact that openssh's configure also breaks when one uses OpenBSD's own mandoc on Linux, so that will fix two issues with one.

**Comment by mjeveritt** [comment]
This looks like the right solution - https://www.spinics.net/lists/openssh-unix-dev/msg05892.html . Trying to find whether/when this may have been merged ..

**Comment by wylfen** [comment]
I'm the author of the mail you linked. As far as I can remember, it was never discussed further and has not been merged.

**Comment by mjeveritt** [comment]
> I'm the author of the mail you linked. As far as I can remember, it was never discussed further and has not been merged.

Thanks for the reply; and what a disappointing conclusion.

Perhaps we can still carry this as a somewhat-less-awful patch in Gentoo - thoughts @anarchpenguin @blueness ?

**Comment by mjeveritt** [comment]
ok consulting with dalias in  #musl IRC channel, we have concluded that `--disable-tmp` is the correct solution here.
This can be gated in the ebuilds with `use elibc_musl` .
I will propose a PR, and consult @chutz as ::gentoo maintainer.

**Comment by anarchpenguin** [comment]
Has already been addressed in ::gentoo for musl users.

**Comment by mjeveritt** [comment]
> Has already been addressed in ::gentoo for musl users.

See https://gitweb.gentoo.org/repo/gentoo.git/commit/net-misc/openssh?id=466c34fd3e7836a9b180dcf320023596a1df0567
