### ISSUE TITLE
net-dialup/ppp-2.4.7-r99 fails to compile

### ISSUE THREAD

**Issue by PaddyMac** [gentoo/musl#57]
[ppp-2.4.7-r99-build.log.txt](https://github.com/gentoo/musl/files/1129340/ppp-2.4.7-r99-build.log.txt)

**Comment by stefson** [comment]
This should be fixed in https://github.com/gentoo/musl/pull/61/commits/ff860c1bb6539cb68f9df84878450535851922a5
