### ISSUE TITLE
high memory consumption of gcc on arm

### ISSUE THREAD

**Issue by stefson** [gentoo/musl#59]
I'm using two chroots to test both glibc and musl stuff for arm. Recently I could not build gcc-5.4.0-r3 because there is only one Gigabyte of Ram on the device, which is not enough to build genautomata. This issue was adressed in #56 , and while the same patch works fine for a glibc based gcc, it does not fully work for the musl based one. 

glibc chroot with the patch from #56 : 3 jobs on 4 cores, 5 hrs 54 minutes
musl chroot with the patch from #56 : fails with 3 jobs, fails with 2 jobs, works with 1 job and takes 12 hrs 40 minutes

they both fail without the patch due to out of memory errors. 

I found a patch for gcc to solve this issue for both genautomata and genattrtab

https://patchwork.ozlabs.org/patch/695293/

but I am not very certain if this can be backported? The patch got merged into gcc-7 , it can be applied to gcc-6.3.0 without problems, but I don't know if this means it will work as expected on gcc-7? The patch fails hard for gcc-5.4.0-r3, I doubt it would be possible to safely backport it, would it?

**Comment by stefson** [comment]
@blueness the Gentoo bug for the toolchain team is here: https://bugs.gentoo.org/show_bug.cgi?id=623156

**Comment by stefson** [comment]
the patch from #56 got merged upstream in gcc-6.4.0, a new and more sophisticated patch for gcc-6.4.0 is to be found here: 

https://github.com/gcc-mirror/gcc/commit/ef0792f1418d7d4b99858e7233cd91dfdf2ad9d0

**Comment by blueness** [comment]
This is not specifically a musl issue.  I know that fixing gcc would require a patch added to the overlay, but it seems to me its already upstream.  So I'm going to close this bug, but reopen if I misunderstood something and need to act.
