### ISSUE TITLE
dev-qt/qtcore-5.9.2:gentoo doesn't link

### ISSUE THREAD

**Issue by karlguy** [gentoo/musl#69]
This might not be a musl related issue, but I have no idea at this point.

**Link to my forum post (contains error logs):** 
https://forums.gentoo.org/viewtopic-t-1071554-highlight-qtcore.html

**Link to build.log**
https://paste.ee/p/wHGU7

**Stuff I tried:**

- Patching source with alpine patches at https://git.alpinelinux.org/cgit/aports/tree/community/qt5-qtbase?h=master
- Using g++ only to compile, as I normally use clang systemwide
- qtcore-5.7.2-r3:musl compiles perfectly fine without any fiddling

**Speculation:**
From what I can see from the build logs, qtcore seems to test for the presence of the gold linker, and forces it's use if it is found, regardless of what is specified by the user. Since the build fails at link time, not compile time, I think this is probably the issue. But I have no idea.

**Sidenote:** 
During the compile process, it forces the use of g++ similarly to how it forces gold, and this is also undesirable

**Comment by lluixhi** [comment]
Does https://github.com/gentoo/musl/commit/28220ab69ae4359ea742a89dea2c127d719b70d0 fix your issue?

**Comment by karlguy** [comment]
Yes it does. Thanks! Closed.
