### ISSUE TITLE
Mesa does not compile properly with video_cards=radeonsi due to endianess check

### ISSUE THREAD

**Issue by Uramekus** [gentoo/musl#74]
used to need [this](https://lists.freedesktop.org/archives/mesa-dev/2016-November/134355.html) to compile mesa-9999 version but applying this patch broke recently

as of today, the patches on the overlay does not apply due to changes on the source [even alpine musl-fixes](https://git.alpinelinux.org/cgit/aports/tree/main/mesa/musl-fixes.patch) doesn't apply and gets rejected on emerging so im opening a [bug](https://bugs.freedesktop.org/show_bug.cgi?id=104034) on their bugzilla

im posting this here to make you guys aware of the status of mesa-git, which is not passing with musl at least on my usecase (radeonsi)
i have checked with VIDEO_CARDS=intel i965 and it does sucessfully compile

**Comment by lluixhi** [comment]
We're aware. We have a similar patch in this overlay right now, and we'll probably patch it again.

**Comment by Uramekus** [comment]
yup, i  personally assumed you guys knew but just couldn't forget to cite this here since it had a possiblity of you guys not knowing it.
 Posted here and made the bugreport because i think its time to have mainline support already, that said, i already having a working patch for me, if anyone want the patch it is here:
[meme.patch](https://github.com/gentoo/musl/files/1524321/meme.txt)
