### ISSUE TITLE
mask idn useflag for net-misc/iputils on musl profiles

### ISSUE THREAD

**Issue by stefson** [gentoo/musl#81]
The compilation issues for net-misc/iputils have been solved with recent 20171016_pre, but according to https://bugs.gentoo.org/604542 the idn part still doesn't seem to work. Quote from the bug: 
`
ATM, musl release is 1.1.18, and support for IDN is now expected for 1.1.20.
Consequently, iputils are still unusable when compiled with idn USE flag, due to lack of support in musl `

So I think this is so horribly broken, it should be masked until musl 1.1.20 get's shipped, right?

**Comment by stefson** [comment]
@blueness - can you please take care of this? People in the linked bug above are asking for it as well.

**Comment by blueness** [comment]
done.  remind me when musl-1.1.20 lands to remove the mask.
