### ISSUE TITLE
Don't break catalyst builds

### ISSUE THREAD

**Issue by blueness** [gentoo/musl#82]
commit d9d10688d06b121fbec7a7658bdc4b931570b2a2 stabilized linux-headers-4.14.  this broke sys-apps/net-tools.  i tried to compensate by c235bfe495684338953b8da7974d4f320d19020d where i stabilized the overlay version of sys-apps/net-tools.  this worked in one environment but not in catalyst.

as a result, stage3 builds are currently broken.  i don't have time to debug this now but it has to be fixed asap.  if we can't resolve this soon, i will have to do a lot of reverting.  i will by jan 10, 2018 if we can't fix this.

i would ask that people please test commits to make sure they don't break stage3 builds.  be careful with any @system packages.  i'm not as picky about non @system so don't worry if you break those, but if you break @system, then i'll be sad.

**Comment by blueness** [comment]
sorry wrong commit for linux-headers.  i'm not sure what changed now, but we need to check that.

**Comment by blueness** [comment]
okay reverting my commit to try to fix the issue fixed it.  i think i may have hit the breakage during the brief time linux-headers-4.13 was off the tree.

again please be careful with @system packages.

**Comment by stefson** [comment]
Uhm, could you solve the problem in the meantime? Cause on amd64 with stable toolchain and linux-headers-4.13, I can't emerge net-tools from the tree but have to stick to the patched one from the overlay.

**Comment by blueness** [comment]
actually its still a problem.  the tree version fails in a chroot while the musl version fails in catalyst builds.  i can't figure out what you guys did with linux-headers.  can you please restore.

**Comment by stefson** [comment]
Sure, I can do runtime testing on arm and amd64 if you'd like me to. For that please state briefly what exactly to test and to look for, right now I'm not really certain. net-utils from the overlay with stable linux-headers-4.13, net-utils from the tree with stable linux-header from the overlay, etc. pp. ?

**Comment by blueness** [comment]
I want a fix so that sys-apps/net-tools builds in both a chroot AND catalyst runs.  can you test both and tell me what needs to be changed on the overlay.

**Comment by blueness** [comment]
what was the state of the sys-apps/net-tools ebuilds and sys-kernel/linux-headers before the recent set of commits and reverts?

**Comment by blueness** [comment]
okay i got it.  it was the order in which things were pushed because the stage3 tarball was using linux-headers-4.4 while the overlay had stabilized 4.13.

**Comment by blueness** [comment]
@everyone, please give me a heads up if you're going to touch any @system packages.
