### ISSUE TITLE
issues with a few languages on musl

### ISSUE THREAD

**Issue by bjornpagen** [gentoo/musl#89]
Many gentoo packages for stuff in dev-lang assume glibc. They break on musl, and are generally messy.

This github issue was made to keep track of them.

One thing in common in **all** of these problems is that the user has no choice but to bootstrap these compilers. What I mean by this is that by default, all of these compilers are bootstrapped from binaries hardcoded in the ebuild. This behavior is bad, because if the ebuild doesn't work on a given architecture, it should be easy for the user to use their own binaries to bootstrap. [A better solution would be a "bootstrap" use flag, as done by Exherbo in their dev-lang packages.](http://git.exherbo.org/arbor.git/tree/packages/dev-lang/go/go-1.9.3.exheres-0)
```
DEPENDENCIES="
    build:
        !bootstrap? ( dev-lang/go )
"
```

- **Golang**

 Go is broken, since the [ebuilds in the gentoo repository](https://github.com/gentoo/gentoo/blob/eca95e70409810b07a07795df3e4a020118479ac/dev-lang/go/go-1.7.1.ebuild) download stages from https://dev.gentoo.org/~williamh/dist, which contain binaries linked against glibc. 

[Exherbo's ebuild](http://git.exherbo.org/arbor.git/tree/packages/dev-lang/go/go-1.9.3.exheres-0) does this in a better way; by downloading stages directly from google. For example, for amd64, there is one stage, and it is libc independent.

- **Rust**

Rust is still broken on musl, because it doesn't compile with `emerge rust`.

- **GHC (Haskell)**

The stage haskell used in [gentoo's ghc ebuild](https://github.com/gentoo/gentoo/blob/eca95e70409810b07a07795df3e4a020118479ac/dev-lang/ghc/ghc-7.10.3.ebuild) is linked against glibc, so the build fails. [Exherbo's ebuild](http://git.exherbo.org/haskell.git/tree/packages/dev-lang/ghc/ghc.exlib) already accounts for musl:
```
DOWNLOADS+="
    bootstrap? (
        platform:amd64? (
            libc:glibc? ( http://code.haskell.org/~slyfox/${PN}-amd64/${PN}-bin-${PV}-amd64.tbz2 )
            libc:musl? ( https://www.somasis.com/dl/ghc-musl-bootstrap/${PNV}-x86_64-pc-linux-musl.tar.xz )
        )
        platform:x86? ( http://code.haskell.org/~slyfox/${PN}-x86/${PN}-bin-${PV}-x86.tbz2 )
    )
"
```

**Comment by gigavinyl** [comment]
Java also is having problems, at least for me. Oracle's jdk is compiled against glibc so that's no good and icedtea depends on icedtea-bin which depends on glibc so that's a no-go too. Do we need a patched version of icedtea-bin?

**Comment by aidanharris** [comment]
In the case of `go` I managed to compile it by using the go-bootstrap ebuild found [here](https://data.gpo.zugaina.org/jamestr/dev-lang/go-bootstrap/). After emerging `go-bootstrap` I changed the hardcoded `GOROOT_BOOTSTRAP` to `GOROOT_BOOTSTRAP="/usr/lib/go1.4"` and it built fine.

**Comment by blueness** [comment]
This is some interest in go on musl right now.  Can you prepare a PR for the musl overlay with the working ebuild.

**Comment by anarchpenguin** [comment]
Open serperate language packages that you would like to see addressed. Please do not bundle them together.
