### ISSUE TITLE
dev-lang/rust does not respect MAKEOPTS from make.conf during bootstrap

### ISSUE THREAD

**Issue by stefson** [gentoo/musl#96]
This is a problem if the build system does not have much ram per thread, or not much in general, or for a possible debug build. I did a bit of research, pullrequest #95 does have the results. For dev-util/cargo the problem has been solved, for dev-lang/rust it has been mitigated by a lot in restricting ./x.py

What is left to be dealt with is the minimal bootstrap between src_configure and the execution of ./x.py ; did a reasonable amount of research about what is going on there, but found nothing helpfull in terms of restricting the jobs, or even make them honor the MAKEOPTS from make.conf 

Therefore, I think it should be okay to commit the pullrequest to the overlay, and to pick up the rest of the problem later on.

**Comment by stefson** [comment]
I'll take with upstream about this.

**Comment by blueness** [comment]
ok
